<?php
/**
 * @package Clearbricks
 *
 * Backwards compatibility with clearbricks < 2.0
 *
 * @copyright Olivier Meunier & Association Dotclear
 * @copyright GPL-2.0-only
 * @version 1.2
 */
declare(strict_types=1);

$src = dirname(__FILE__) . '/src';

if (!isset($__autoload) || !is_array($__autoload)) {
    $__autoload = [];
}

# Common class are loaded in src/Common/_main.php
$__autoload = array_merge($__autoload, [
    'cursor'                    => $src . '/Database/Layer/Cursor.php',
    'i_dbLayer'                 => $src . '/Database/Layer/InterfaceLayer.php',
    'dbLayer'                   => $src . '/Database/Layer/Layer.php',
    'record'                    => $src . '/Database/Layer/Record.php',
    'staticRecord'              => $src . '/Database/Layer/StaticRecord.php',
    'mysqliConnection'          => $src . '/Database/Layer/Driver/Mysqli.php',
    'mysqlimb4Connection'       => $src . '/Database/Layer/Driver/Mysqlimb4.php',
    'mysqliConnection'          => $src . '/Database/Layer/Driver/Pgsql.php',
    'sqliteConnection'          => $src . '/Database/Layer/Driver/Sqlite.php',
    'dbStruct'                  => $src . '/Database/Schema/Struct.php',
    'dbStructTable'             => $src . '/Database/Schema/StructTable.php',
    'i_dbSchema'                => $src . '/Database/Schema/InterfaceSchema.php',
    'dbSchema'                  => $src . '/Database/Schema/Schema.php',
    'mysqliSchema'              => $src . '/Database/Schema/Driver/Mysqli.php',
    'mysqlimb4Schema'           => $src . '/Database/Schema/Driver/Mysqlimb4.php',
    'pgsqlSchema'               => $src . '/Database/Schema/Driver/Pgsql.php',
    'sqliteSchema'              => $src . '/Database/Schema/Driver/Sqlite.php',
    'diff'                      => $src . '/Diff/Diff.php',
    'tidyDiff'                  => $src . '/Diff/TidyDiff.php',
    'tidyDiffChunk'             => $src . '/Diff/TidyDiffChunk.php',
    'tidyDiffLine'              => $src . '/Diff/TidyDiffLine.php',
    'filemanager'               => $src . '/File/Manager/Manager.php',
    'fileItem'                  => $src . '/File/Manager/Item.php',
    'fileZip'                   => $src . '/File/Zip/Zip.php',
    'fileUnzip'                 => $src . '/File/Zip/Unzip.php',
    'htmlFilter'                => $src . '/Html/Filter.php',
    'htmlValidator'             => $src . '/Html/Validator.php',
    'formComponent'             => $src . '/Html/Form/Component.php',
    'formForm'                  => $src . '/Html/Form/Form.php',
    'formTextarea'              => $src . '/Html/Form/Textarea.php',
    'formInput'                 => $src . '/Html/Form/Input.php',
    'formCheckbox'              => $src . '/Html/Form/Checkbox.php',
    'formColor'                 => $src . '/Html/Form/Color.php',
    'formDate'                  => $src . '/Html/Form/Date.php',
    'formDatetime'              => $src . '/Html/Form/Datetime.php',
    'formEmail'                 => $src . '/Html/Form/Email.php',
    'formFile'                  => $src . '/Html/Form/File.php',
    'formHidden'                => $src . '/Html/Form/Hidden.php',
    'formNumber'                => $src . '/Html/Form/Number.php',
    'formPassword'              => $src . '/Html/Form/Password.php',
    'formRadio'                 => $src . '/Html/Form/Radio.php',
    'formTime'                  => $src . '/Html/Form/Time.php',
    'formUrl'                   => $src . '/Html/Form/Url.php',
    'formLabel'                 => $src . '/Html/Form/Label.php',
    'formFieldset'              => $src . '/Html/Form/Fieldset.php',
    'formLegend'                => $src . '/Html/Form/Legend.php',
    'formSelect'                => $src . '/Html/Form/Select.php',
    'formOptgroup'              => $src . '/Html/Form/Optgroup.php',
    'formOption'                => $src . '/Html/Form/Option.php',
    'pager'                     => $src . '/Html/Pager.php',
    'imageMeta'                 => $src . '/Image/Meta.php',
    'imageTools'                => $src . '/Image/Tools.php',
    'mail'                      => $src . '/Mail/Mail.php',
    'mailConvert'               => $src . '/Mail/Convert.php',
    'socketMail'                => $src . '/Mail/Socket.php',
    'mimeMessage'               => $src . '/Mail/Message.php',
    'netSocket'                 => $src . '/Network/Socket/Socket.php',
    'netSocketIterator'         => $src . '/Network/Socket/Iterator.php',
    'netNntp'                   => $src . '/Network/Nntp/Nntp.php',
    'nntpMessage'               => $src . '/Network/Nntp/Message.php',
    'netHttp'                   => $src . '/Network/Http/Http.php',
    'HttpClient'                => $src . '/Network/Http/Client.php',
    'feedParser'                => $src . '/Network/Feed/Parser.php',
    'feedReader'                => $src . '/Network/Feed/Reader.php',
    'xmlrpcException'           => $src . '/Network/Xmlrpc/Exception.php',
    'xmlrpcValue'               => $src . '/Network/Xmlrpc/Value.php',
    'xmlrpcMessage'             => $src . '/Network/Xmlrpc/Message.php',
    'xmlrpcRequest'             => $src . '/Network/Xmlrpc/Request.php',
    'xmlrpcDate'                => $src . '/Network/Xmlrpc/Date.php',
    'xmlrpcBase64'              => $src . '/Network/Xmlrpc/Base64.php',
    'xmlrpcClient'              => $src . '/Network/Xmlrpc/Client.php',
    'xmlrpcClientMulticall'     => $src . '/Network/Xmlrpc/ClientMulticall.php',
    'xmlrpcServer'              => $src . '/Network/Xmlrpc/Server.php',
    'xmlrpcIntrospectionServer' => $src . '/Network/Xmlrpc/IntrospectionServer.php',
    'restServer'                => $src . '/Rest/Server.php',
    'sessionDB'                 => $src . '/Session/SessionDb.php',
    'template'                  => $src . '/Template/Template.php',
    'tplNode'                   => $src . '/Template/Node.php',
    'tplNodeBlock'              => $src . '/Template/NodeBlock.php',
    'tplNodeText'               => $src . '/Template/NodeText.php',
    'tplNodeValue'              => $src . '/Template/NodeValue.php',
    'tplNodeBlockDefinition'    => $src . '/Template/NodeBlockDefinition.php',
    'tplNodeValueParent'        => $src . '/Template/NodeValueParent.php',
    'wiki2xhtml'                => $src . '/Text/Wiki2xhtml.php',
    'urlHandler'                => $src . '/Url/Handler.php',
    'xmlTag'                    => $src . '/Xml/Tag.php',
    'xmlsql'                    => $src . '/Xml/Sql.php',
    'IXR_Value'                 => $src . '/Xml/Incutio/IXR_Value.php',
    'IXR_Message'               => $src . '/Xml/Incutio/IXR_Message.php',
    'IXR_Server'                => $src . '/Xml/Incutio/IXR_Server.php',
    'IXR_Request'               => $src . '/Xml/Incutio/IXR_Request.php',
    'IXR_Client'                => $src . '/Xml/Incutio/IXR_Client.php',
    'IXR_Error'                 => $src . '/Xml/Incutio/IXR_Error.php',
    'IXR_Date'                  => $src . '/Xml/Incutio/IXR_Date.php',
    'IXR_Base64'                => $src . '/Xml/Incutio/IXR_Base64.php',
    'IXR_IntrospectionServer'   => $src . '/Xml/Incutio/IXR_IntrospectionServer.php',
    'IXR_ClientMulticall'       => $src . '/Xml/Incutio/IXR_ClientMulticall.php',
]);
